### ISSUE TITLE
#Feature request - Adding pre-defined private key for the search mode

### ISSUE THREAD

**Issue by exterity** [kanhavishva/KeyHunt-Cuda#17]
Hi @kanhavishva,

Thank you for the new update.

May you please consider to add the feature "pre-defined private key" for the search mode? Lets say I have a bunch of private key in a text file, about 10 or 100 billion keys per text file, line by line. These keys does not follow any sequential orders by its value.

The KeyHunt-Cuda will load those private keys and brute force the target wallet addresses.

IMHO, this is way more flexible for users who does not want to use the random, or stride or rstride mode to find the private key.

Thank you.

**Comment by WanderingPhilosopher** [comment]
If you have the private keys, why do you need to search for them? Makes no sense.

**Comment by exterity** [comment]
Ah, because formerly I don't understand the code and the way it works clearly then I though might be the program searchs the key faster with the text file. Those keys generated by a specific algorigthm to which I've managed to code them via C#. But for now, I understand a bit of the Keyhunt C++ code, using the bloom filter for my purpose. You are right, I don't need it for KeyHunt-Cuda. Thanks for your comment.
