### ISSUE TITLE
How to use addresses_to_hash160.py 

### ISSUE THREAD

**Issue by klfkl** [kanhavishva/KeyHunt-Cuda#29]
which command to use this.i can't run... please help

**Comment by alipostaci2001** [comment]
1- your btc_addresses.txt       : that is your btc addresses file
2-btc_addresses.bin              : that is for Keyhunt
-----------------python3  yourbtc_addresesses.txt btc_addresses.bin

**Comment by kanhavishva** [comment]
first install ```python3 -m pip install base58```.
then run ```python3 addresses_to_hash160.py your_address_input_file.txt hash160_output_file.bin```

**Comment by klfkl** [comment]
Thanx everyone
