### ISSUE TITLE
bloom not initialized!

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/KeyHunt-Cuda#3]
why could it be
i do:
1. b58dec.exe addr.txt addr.r160
2. RMD160-Sort.exe addr.r160 addr.bin
3. KeyHunt-Cuda.exe -t 2 -e -n 15 -f addr.bin
KeyHunt-Cuda v1.03

[addr.txt](https://github.com/kanhavishva/KeyHunt-Cuda/files/6221746/addr.txt)
[my output.txt](https://github.com/kanhavishva/KeyHunt-Cuda/files/6221767/my.output.txt)

**Comment by kanhavishva** [comment]
address number should be more than 1000 for proper bloom initialization. 

right now codes is going through a lot of changes so always check github for new features.

**Comment by Noname400** [comment]
Thanks for the quick response.
I think I should add this to the description.
Bloom Filter >= 1000 address
