### ISSUE TITLE
There are still questions.

### ISSUE THREAD

**Issue by Noname400** [kanhavishva/KeyHunt-Cuda#5]
Good day.
thank you for your work.
but there are still questions.
1.why does the program not find keys if -t 0
2. Does the program look for keys randomly or sequentially? as I understood from the code and the program, only the base key is randomly selected. then the program searches with the usual search + 1 + 1 + 1 + 1 + 1 + 1 and so on.
3. Could you add a random search function. (for puzzle # 64 this would be relevant)

**Comment by kanhavishva** [comment]
1. check latest release
2. previously program was choosing a random base key and then keep incrementing it.
3. for now I removed random mode completely, and added ranging feature, check the 1.04

**Comment by Noname400** [comment]
As I understand it, version 1.04 also lacks random mode.
are you planning to add it in future versions?

Thank you so much for your work and patience.

**Comment by kanhavishva** [comment]
For now I removed random feature completely because it was from parent repository, and was not fitting in my requirements. 

Yes, I will add all the features in the future.

Welcome.

**Comment by exterity** [comment]
> Good day.
> thank you for your work.
> but there are still questions.
> 1.why does the program not find keys if -t 0
> 2. Does the program look for keys randomly or sequentially? as I understood from the code and the program, only the base key is randomly selected. then the program searches with the usual search + 1 + 1 + 1 + 1 + 1 + 1 and so on.
> 3. Could you add a random search function. (for puzzle # 64 this would be relevant)

Hi @Noname400 Where to find in the code for the key that is sequentially by adding + 1 + 1 +1 ? I would like to modify it to jump to the next key by sequent of 10 + 10 + 10....
May you advise me.
Thank you.

**Comment by Noname400** [comment]
> > Добрый день. 
> > Спасибо вам за вашу работу. 
> > но есть еще вопросы. 
> > 1. почему программа не находит ключи, если -t 0 
> > 2. Программа ищет ключи случайным образом или последовательно? как я понял из кода и программы случайно выбирается только базовый ключ. затем программа поиск с обычным поиском + 1 + 1 + 1 + 1 + 1 + 1 и так далее. 
> > 3. Не могли бы вы добавить функцию случайного поиска. (для головоломки №64 это будет актуально)
> 
> Hi @ Noname400 найти в коде ключ то есть Где последовательно добавлением + 1 + 1 +1? Я хотел бы изменить его, чтобы перейти к следующему ключу последовательностью 10 + 10 + 10 ....
> ли вы мне посоветовать.
> Спасибо.

Вам нужна версия https://github.com/kanhavishva/BitCrack2
--rstride N             Random stride bits, continue after end of range by setting up new random stride, Where N in hex format

**Comment by exterity** [comment]
Thank you @Noname400.

However, for this version, KeyHunt-Cuda? Is it possible to change?

**Comment by Noname400** [comment]
в чем разница это версии и той?
я особо не заметил.
можете сказать ?

**Comment by exterity** [comment]
@Noname400 I just "feel" this version is working faster than the "BitCrack" style version :)
